# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'hongkimDaonProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for hongkimDaonProject
  pod 'SwiftLint'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
end
