# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'hongkimDaonProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  inhibit_all_warnings!

  # Pods for hongkimDaonProject
  pod 'SwiftLint'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/DynamicLinks'
  pod 'FirebaseFirestoreSwift', '> 8.14.0-beta'
  pod 'SideMenu'
  pod 'Tabman', '~> 2.9'
  pod 'SnapKit', '~> 5.0.0'
  pod 'FMPhotoPicker', '~> 1.3.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Firebase/Messaging' 
  pod 'IQKeyboardManagerSwift'
  pod 'STTextView'
  pod 'lottie-ios'
end
